version: "3"
services:
  mysql8:
    image: mysql:8.0.30
    container_name: mysql8
    hostname: mysql8
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql8-data:/var/lib/mysql
    networks:
      - hadoop_hadoop_network

  nacos-server:
    image: nacos/nacos-server:v2.3.2
    hostname: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql8
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=sky_nacos_server
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_DATABASE_NUM=1
      - DB_POOL_CONNECTION_TIMEOUT=30000
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      - NACOS_AUTH_IDENTITY_KEY=AAA
      - NACOS_AUTH_IDENTITY_VALUE=BBB
    networks:
      - hadoop_hadoop_network

  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file


volumes:
  esdata:
  mongodb-data:
  dinky-data:
  mysql8-data:
  minio-data:


# 连接外部网络
networks:
  hadoop_hadoop_network: