version: "3"
services:
  mysql8:
    image: mysql:8.0.30
    container_name: mysql8
    hostname: mysql8
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql8-data:/var/lib/mysql
    networks:
      - hadoop_hadoop_network



  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file


volumes:
  esdata:
  mongodb-data:
  dinky-data:
  mysql8-data:
  minio-data:


# 连接外部网络
networks:
  hadoop_hadoop_network: