server:
  port: 8900
  servlet:
    context-path: /account


spring:
  application:
    name: account-service
  sql:
    init:
      mode: embedded
      platform: mysql

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/account?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root