server:
  port: 8902
  servlet:
    context-path: /storage



spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storage?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root